apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinedeployment
  labels:
    app: pipelinedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinedeployment
  template:
    metadata:
      labels:
        app: pipelinedeployment
    spec:
      imagePullSecrets:
        - name: "dhubauth"
      containers:
       - name: pipelinedeployment-container
         image: prince162222/pipelinetest:latest
         imagePullPolicy: Always
         ports:
            - containerPort: 80
            - containerPort: 443
