apiVersion: v1
kind: Service
metadata:
  name: pipelinetestservice
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 31004
  selector:
    app: pipelinedeployment
      
