apiVersion: v1
kind: Service
metadata:
  name: pipelineservice
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 31004
  selector:
    app: pipelinedeployment
      
