apiVersion: v1
kind: Service
metadata:
  name: pipelineservice
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31821
  selector:
    app: pipelinedeployment
      
