apiVersion: v1
kind: Service
metadata:
  name: pipelineservice
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 80
    - name: https
      protocol: TCP
      port: 8086
      targetPort: 443
  selector:
    app: pipelinedeployment
      
